### ISSUE TITLE
Colour scheme of list view

### ISSUE THREAD

**Issue by hsrai** [Software-Development-Centre-GNE/SnC#1]
Improve it.

**Comment by geekabhinav007** [comment]
Color Layout color Improved anf fixed

**Comment by hsrai** [comment]
Colour scheme is still not appropriate.

**Comment by geekabhinav007** [comment]
Please provide color scheme you think fit perfectly fine.

1. Provide color code of body.
2. Provide color code of button
3. Provide color code of list.

**Comment by geekabhinav007** [comment]
Color Schema improved need review from others community member.

**Comment by geekabhinav007** [comment]
> Color Schema improved need review from others community member.

I think it's resolved, So, I am closing it.
