### ISSUE TITLE
Improve User Interface

### ISSUE THREAD

**Issue by Mr-codehunter** [Software-Development-Centre-GNE/SnC#11]
1. Improve some `user interface` and make it more interactive.

2. The `eye icon` ( review ) is not working.

3. Add some 3D images on the screen.

4. `VIEW ALL` button is not working.

**Comment by geekabhinav007** [comment]
Issue number 4 is resolved #13

**Comment by geekabhinav007** [comment]
issue 2 is resolved removed eye icon because we don't need that instead of that download and description icon added.

**Comment by geekabhinav007** [comment]
Most of the things done.
Please review.
