### ISSUE TITLE
Home screen

### ISSUE THREAD

**Issue by hsrai** [Software-Development-Centre-GNE/SnC#3]
Refer [ScreenShot](https://software-development-centre-gne.github.io/SnC/#home-screen)

![ScreenShot](https://software-development-centre-gne.github.io/SnC/MobAppHomeScreen.png)

Issues are:

1. In landscape mode, things are Ok, but in portrait, the two buttons in first row, looks like a single. Separate these two buttons.
2. Text in button 1, is cropped.
3. For buttons, it is suggested to to use icons, created as .svg graphics. A [sample](https://www.svgrepo.com/show/315879/movie-film.svg)

**Comment by hsrai-yahoo** [comment]
A better option [https://github.com/topics/svg-icons](https://github.com/topics/svg-icons)

**Comment by 13-Joban** [comment]
Made changes in Home Screen.
https://github.com/Software-Development-Centre-GNE/SnC/pulls

**Comment by geekabhinav007** [comment]
It's Fixed, It is tested.
fixed by following PR
#4 
I

**Comment by hsrai** [comment]
SVG icons not incorporated.

Text is being trimmed.

**Comment by geekabhinav007** [comment]
> added icons need review

It is SVG icon or different?

**Comment by 13-Joban** [comment]
> > added icons need review
> 
> It is SVG icon or different?

it is vector icon predefined in android studio we can also import our own.

**Comment by geekabhinav007** [comment]
Reviewed working fine  #21
